- nama : madu habbat 
  deskripsi: Madu adalah makanan yang mengandung aneka nutrisi seperti protein, asam amino, karbohidrat, vitamin, mineral, dekstrin, pigmen tumbuhan dan komponen aromatik. Madu mengandung 11 asam amino esensial yang tidak diproduksi oleh tubuh. Dari hasil penelitian terbaru, zat-zat atau senyawa yang ada di dalam madu sangat komplek yaitu mencapai 181 jenis.
  komposisi: madu
  isi: 250gr
  harga: 130,000
  img: 
  mata_uang: Rp. 

- nama : madu multiflora
  deskripsi: Madu Asli Multiflora Merupakan madu alami tanpa tambahan bahan lain yang terjamin mutu dan keasliannya serta lebih terjaga keutuhan kandungan gizinya. Dihasilkan dari lebah madu ung-gul “Apis Mellifera”, kaya akan vitamin, mineral, enzim, protein, hormon-hormon, serta zat antimikroba dan zat antibiotik. Madu Asli Multiflora telah lulus kendali mutu yang ketat dan mempunyai kadar air yang rendah sehingga tidak terjadi proses fermentasi.
  komposisi: madu
  isi: 250gr
  harga: 100,000
  mata_uang: Rp. 

- nama : Extra Food
  deskripsi: Extra Food suplemen kesehatan alami yang dibuat dari sinergi 23 herbal yang kaya akan antioksidan & serat alami. Mengkonsumsi Extra Food memberikan perlindungan Anda dan keluarga dari radikal bebas.
  komposisi: Sari kurma, madu alami, royal jelly, bee polen, bayam merah, wortel, beras hitam, rosella ungu, habbatussauda, zaitun, blueberry, blackberry, daun ashitaba, curcuma, kulit manggis, daun sirsak, plum hitam, anggur hitam, spirulina, daun stevia, meniran, strawberry.
  isi: 250ml
  harga: 80,000
  mata_uang: Rp. 

- nama: madu s jaga
  deskripsi: Madu S Jaga mengandung bahan-bahan terpilih dari alam yang sangat bermanfaat untuk tubuh. Madu S Jaga merupakan produk yang diracik secara khusus dari Madu, Sari Kurma murni, Spirulina, Pegagan, Ilalang, Sambiloto dan Daun Sirsak dengan komposisi yang tepat.
  komposisi: Madu Multiflora, Sari Kurma Murni, dan Ekstrak Herbal Alami (Spirulina, Pegagan, Ilalang, Sambiloto, Daun Sirsak)
  isi: 285gr
  harga: 120,000
  mata_uang: Rp. 

- nama: madu pahit
  deskripsi: madu yang diproduksi dari lebah Apis Dorsata yang mengkonsumsi nektar dari kuncup pohon yang pahit seperti tanaman kirinyuh, pohon jati, pohon mahoni, tanaman benalu dan tanaman Clidemia Hirta atau tanaman keduduk bulu. Madu Pahit memiliki kandungan alkaloid yang cukup tinggi yang berfungsi sebagai bakteri alami yang membunuh bakteri yang dapat merugikan tubuh.
  komposisi: madu 100%
  isi: 250 gr
  harga: 120,000
  mata_uang: Rp. 

- nama: madu kental
  deskripsi: madu dari nektar buah longan
  komposisi: 100% madu asli (natural pure honey)
  isi: 250 gr
  harga: 250,000
  mata_uang: Rp. 